source 'https://rubygems.org'
#source 'https://gems.ruby-china.com'
#source 'https://mirrors.tuna.tsinghua.edu.cn/rubygems/'

if ENV['DEV']
  puts 'Development Mode'
  gem 'cocoapods', :path => '../cocoapods'
  gem 'cocoapods-spm', :path => '../cocoapods-spm'
  gem 'debug'
else
  gem 'cocoapods'
  gem 'cocoapods-spm'
end
