source 'https://rubygems.org'
#source 'https://gems.ruby-china.com'
#source 'https://mirrors.tuna.tsinghua.edu.cn/rubygems/'

if ENV['DEV']
  gem 'cocoapods', :path => '../cocoapods'
  gem 'cocoapods-spm', :path => '../cocoapods-spm'

  # for Debug in VSC
  gem "ruby-lsp"
  gem "rubocop"
else
  gem 'cocoapods'
  gem 'cocoapods-spm'
end
