source 'https://rubygems.org'
#source 'https://gems.ruby-china.com'
#source 'https://mirrors.tuna.tsinghua.edu.cn/rubygems/'

if ENV['DEV']
  puts 'Development Mode'
  gem 'cocoapods', :path => '../cocoapods'
  gem 'cocoapods-spm', :path => '../cocoapods-spm'

  # for Debug in VSC
  gem "ruby-lsp"
  gem "rubocop"
  gem "rubocop-packaging"
  gem "rubocop-performance"
  gem "rubocop-rspec"
  gem "rubocop-shopify"
  gem "rubocop-thread_safety"
else
  gem 'cocoapods'
  gem 'cocoapods-spm'
end
