platform :ios, '13.0'
install! 'cocoapods', :generate_multiple_pod_projects => true
target 'AppDemo' do
  pod 'PodDemo', :path => '../PodDemo/PodDemo.podspec'
  spm_pkg "MacroDemo", :path => '../MacroDemo'
end
